### PR TITLE
Add missing glyphs for MES-1

### PR DESCRIPTION
**Pull request by jublo**
See #52.

bildschirmfoto 2015-10-13 um 15 27 02

### CODE REVIEW

**Comment by jublo** [comment]
Italic style:

bildschirmfoto 2015-10-13 um 15 41 55

**Comment by jublo** [comment]
Bold style:

bildschirmfoto 2015-10-13 um 16 05 42

**Comment by jublo** [comment]
Detail views:

bildschirmfoto 2015-10-13 um 15 52 32
bildschirmfoto 2015-10-13 um 15 54 59

**Comment by jublo** [comment]
BoldItalic style:

bildschirmfoto 2015-10-13 um 16 12 54

**Comment by chrissimpkins** [comment]
@schierlm : Any feedback on these glyphs?  @jublo designed these based upon your MES-1 issue report request.

@jublo : I don't have any experience with `Ldot` and `ldot` styles.  How did you decide on the point size there?  Any idea if this is how they commonly appear?  The points seem large in the bold sets.  Not a criticism, just a first impression.

**Comment by schierlm** [comment]
I would expect the dot in Ŀŀ to match the dot in other dot-accented letters like ė or ẹ or even i. I think Hack uses a more squared dot (like the ones in the ĳ glyph) for that than in the new Ŀŀ glyph.

Also, I have the impression that the stem of the note looks too short (or too thick). But that may be my preference, I can perfectly live with the current one too if the ŀ dots get aligned better to the other dots. :)

**Comment by chrissimpkins** [comment]
That's very helpful.  Thank you very much.  I will talk with JM about it.  We are tentatively slating this as part of the next general release which should come out ~ next week.

**Comment by jublo** [comment]
Would you like to see the note reach more down, like in this photo?

bildschirmfoto 2015-10-15 um 17 40 31

**Comment by jublo** [comment]
@schierlm Thanks for the Ldot input. How do you like these ones?

bildschirmfoto 2015-10-15 um 17 36 52

**Comment by jublo** [comment]
Here are updated variants:

bildschirmfoto 2015-10-15 um 19 04 02
bildschirmfoto 2015-10-15 um 19 02 01

**Comment by jublo** [comment]
@schierlm Please try out these test builds that include the characters from this PR:

* [Hack-Regular.ttf](https://github.com/jublonet/Hack/blob/380de30638978c0807c2a0fa5d20a97c68a6cef4/source/development/jublonet/Hack-Regular.ttf?raw=true)
* [Hack-Italic.ttf](https://github.com/jublonet/Hack/blob/380de30638978c0807c2a0fa5d20a97c68a6cef4/source/development/jublonet/Hack-Italic.ttf?raw=true)
* [Hack-Bold.ttf](https://github.com/jublonet/Hack/blob/380de30638978c0807c2a0fa5d20a97c68a6cef4/source/development/jublonet/Hack-Bold.ttf?raw=true)
* [Hack-BoldItalic.ttf](https://github.com/jublonet/Hack/blob/380de30638978c0807c2a0fa5d20a97c68a6cef4/source/development/jublonet/Hack-BoldItalic.ttf?raw=true)

Comments? :)

**Comment by schierlm** [comment]
Testing the fonts right now and I really like the new glyphs (both the ŀĿ and the note symbol).

However, it seems that 4 glyphs I'm pretty sure that I saw before (which are part of the MES-1 set) are gone in this test build. In particular, these are ŉΩ (which I think I have seen before) and Ŭŭ (which should have been part of the Esperanto pull request). Testing it with WordPad on Windows 7 in case it matters (and I did not restart my computer after installing the new versions yet).

**Comment by jublo** [comment]
I have missed Ŭŭ, that’s right. Regarding ŉΩ, we’ll have to ask @chrissimpkins about them.

Searching the Ŭŭ now, to include them.

**Comment by chrissimpkins** [comment]
We can include all glyphs in the  MES-1 set.  Let's take this potential issue for European users out of the equation, irrespective of use cases in source code.  @jublo do you plan to make these.  I can add them if you are working on other things.

**Comment by chrissimpkins** [comment]
U breve glyphs should be in the ufo files in my development directory @jublo.  they are in the v2.016 release and I worked on them in my own ufo files as I recall.

**Comment by jublo** [comment]
@chrissimpkins Please work on ŉΩ yourself, while I think that Ω is already included. See my UFO just pushed.

**Comment by chrissimpkins** [comment]
will do.  There is an omega in the Greek set.  This must be a different unicode position.  Will check

**Comment by schierlm** [comment]
Greek Omega U+03A9 is present, yes, but Ohm U+2126 is missing in the build above. I uninstalled Hack, rebooted the machine, and re-installed what I had before (v 2.010), and it includes both Ω and Ω. I then repeated the process with the build above (again uninstall and reinstall) to double check that it does not include the Ohm any more... [or perhaps Windows is not the best tool to test this :)]

That ŉ was already mentioned in #52, I did not see it when checking again (my fault)...

**Comment by chrissimpkins** [comment]
@schierlm thank you very much.  We will confirm that both glyphs are included.  This is planned for the next release.

**Comment by jublo** [comment]
Here are new `IJ` and `ij` glyphs:

bildschirmfoto 2015-10-19 um 13 32 03
bildschirmfoto 2015-10-19 um 13 32 29
bildschirmfoto 2015-10-19 um 13 32 42
bildschirmfoto 2015-10-19 um 13 32 59

**Comment by jublo** [comment]
Adding `napostrophe` `U+0149`:

bildschirmfoto 2015-10-22 um 17 53 16
bildschirmfoto 2015-10-22 um 17 56 36

**Comment by jublo** [comment]
@chrissimpkins Please note that AGL has inconsistency, which might be a source of confusion with the glyph:

```
03A9	'GREEK CAPITAL LETTER OMEGA'   (no AGL label)
2126	Omega 'OHM SIGN'               (wrong AGL label)
```

@schierlm Please try out these test builds that include the characters you mentioned, in particular `U+0149`, `U+03A9` and `U+2126`.

* [Hack-Regular.ttf](https://github.com/jublonet/Hack/blob/b3f390e17cde2c9abbf45fb42cc3298f05f0e910/source/development/jublonet/Hack-Regular.ttf?raw=true)
* [Hack-Italic.ttf](https://github.com/jublonet/Hack/blob/b3f390e17cde2c9abbf45fb42cc3298f05f0e910/source/development/jublonet/Hack-Italic.ttf?raw=true)
* [Hack-Bold.ttf](https://github.com/jublonet/Hack/blob/b3f390e17cde2c9abbf45fb42cc3298f05f0e910/source/development/jublonet/Hack-Bold.ttf?raw=true)
* [Hack-BoldItalic.ttf](https://github.com/jublonet/Hack/blob/b3f390e17cde2c9abbf45fb42cc3298f05f0e910/source/development/jublonet/Hack-BoldItalic.ttf?raw=true)

Comments? :)

**Comment by burodepeper** [comment]
I've never heard of the napostrophe. Since it is slightly out of the glyph box, does this conflict in any context the character might be used in?

The italic/bold/IJ looks great btw!

**Comment by schierlm** [comment]
Ohm still does not render for me:

image

but it is the only character that is missing from MES-1 coverage now :)

image

**Comment by jublo** [comment]
@schierlm Which font scanner are you using?

**Comment by chrissimpkins** [comment]
@schierlm I’m with @jublo, what application is that Michael?  That would be extremely helpful to us.

**Comment by schierlm** [comment]
It's the Font Statistics function of http://intltyper.sourceforge.net/sharp/

Yes, I'm aware that it currently only supports the Basic Multilingual Plane (so no surrogate pairs and no unicode codepoints above U+FFFF), but that is a limitation of .NET and I did not find a good way to work around it in .NET.

**Comment by chrissimpkins** [comment]
@schierlm thank you!

**Comment by jublo** [comment]
@schierlm Confirming that U+2126 is missing in the test builds. Looking into why.

**Comment by jublo** [comment]
@schierlm Please test this new build, now properly hinted, and including all of

- Mac Roman
- Windows 1252
- MES-1 —including `U+2126`

* [Hack-Regular.ttf](https://github.com/jublonet/Hack/blob/7cfef300b70e00dd6727a6373c667a122efb8b3c/source/development/jublonet/Hack-Regular.ttf?raw=true)
* [Hack-Italic.ttf](https://github.com/jublonet/Hack/blob/7cfef300b70e00dd6727a6373c667a122efb8b3c/source/development/jublonet/Hack-Italic.ttf?raw=true)
* [Hack-Bold.ttf](https://github.com/jublonet/Hack/blob/7cfef300b70e00dd6727a6373c667a122efb8b3c/source/development/jublonet/Hack-Bold.ttf?raw=true)
* [Hack-BoldItalic.ttf](https://github.com/jublonet/Hack/blob/7cfef300b70e00dd6727a6373c667a122efb8b3c/source/development/jublonet/Hack-BoldItalic.ttf?raw=true)

**Comment by schierlm** [comment]
Looks fine to me :)

**Comment by chrissimpkins** [comment]
Merge to release build in the works for upcoming v2.017.  Thanks for this suggestion and all of your help with the testing Michael (@schierlm).  We really appreciate it.  Should have this out this week.

@jublo & @burodepeper Really nice work on these glyphs.  They look great.  Excellent addition to the sets.

**Pull request merged**
