### PR TITLE
Added information about installation on Gentoo

### PR DESCRIPTION
**Pull request by amadio**
Hack is available on Gentoo. It would be nice to make it visible in the README.md file. Thanks!

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thank you very much for adding this!  Are you managing the package on Gentoo by any chance?

**Comment by chrissimpkins** [comment]
Merged to master

**Comment by amadio** [comment]
Yes, I am packaging Hack on Gentoo. Thanks for merging my pull request. Cheers,

**Comment by chrissimpkins** [comment]
Do you like to be contacted when we push a new release or will you be following this?

**Comment by amadio** [comment]
Being contacted would be nice, as I may miss the releases via GitHub notification. Thanks!

**Comment by chrissimpkins** [comment]
Sounds good.  I will try to poke you.  Thanks for pulling this package together.  It is greatly appreciated!

**Comment by chrissimpkins** [comment]
Added you to our contributors list as well. Thanks again!

**Comment by chrissimpkins** [comment]
@amadio v2.020 is now available in releases Guilherme

**Comment by amadio** [comment]
@chrissimpkins Updated, thanks!

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=71d34d2678ff9f3cef3349935974d8a32bf13e51

**Comment by chrissimpkins** [comment]
@amadio thanks for managing this package! it is greatly appreciated.

**Pull request merged**
