### PR TITLE
Simplify README/documentation (WORK IN PROGRESS)

### PR DESCRIPTION
**Pull request by burodepeper**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
can't merge from my phone.  must be merge conflicts.  will do it tonight

**Comment by burodepeper** [comment]
No rush, I'll let you know when I have a first "complete" version. Currently finishing up on it.

**Comment by burodepeper** [comment]
I've trimmed it down as economically as I could. I think it's time to discuss this version. See https://github.com/burodepeper/Hack/blob/readme/README.md for a rendered version, but be sure to check the source for some additional comments.

I haven't changed anything yet about the new documents I've created in `/docs`. I'm sure they could use some love as well.

**Comment by chrissimpkins** [comment]
@texhex See the Windows sections of the work in progress from David that was merged to the readme branch.  These are split into a default approach in the README file and a more detailed description in the INSTALLATION.md page under the new docs directory

https://github.com/chrissimpkins/Hack/tree/readme

**Comment by texhex** [comment]
@chrissimpkins Saw it, I'm already reviewing it.

**Pull request merged**
