### PR TITLE
Remove svg web fonts

### PR DESCRIPTION
**Pull request by zachleat**
See https://twitter.com/bram_stein/status/506812176212824066

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks for submitting this Zach.  I opened this up for further comment in #88.  Would it be possible to provide further background and justification there?  Can we assume that there is broad use of these versions of the browsers at this point?  The fact that Typekit entirely removed support seems to argue that this will be ok.

**Comment by zeyadj** [comment]
LeavE a comment

**Comment by chrissimpkins** [comment]
@zachleat We eventually did this :)  You were correct

**Comment by zachleat** [comment]
ah, thanks! Sorry I forgot to respond :(

**Comment by chrissimpkins** [comment]
No worries at all.  Just feedback so that you know that I didn't forget :)

**Pull request closed without merging**
